config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :microposts, only: [:create, :destroy]
    resources :relationships, only: [:index, :create, :destroy]
    resources :account_activations, only: [:edit]
  end
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  attr_reader :remember_token, :activation_token

  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
    foreign_key: "follower_id",
    dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
    foreign_key: "followed_id",
    dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name,  presence: true,
    length: {maximum: Settings.maximum_name_length}
  validates :email, presence: true,
    length: {maximum: Settings.maximum_email_length},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.minimum_password_length}, allow_nil: true

  before_save :email_downcase
  before_create :create_activation_digest

  has_secure_password

  class << self
    def digest string
      if cost = ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated? attribute, token
    digest = send("#{attribute}_digest")
    return false unless digest
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update remember_digest: nil
  end

  def current_user? user
    self == user
  end

  def follow other_user
    following << other_user
  end

  def unfollow other_user
    following.delete other_user
  end

  def following? other_user
    following.include? other_user
  end

  def activate
    update activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def email_downcase
    email.downcase!
  end

  def create_activation_digest
    self.activation_token  = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.where(activated: true).paginate page: params[:page],
      per_page: Settings.per_page_count
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      @user.send_activation_email
      flash[:info] = t ".check_activate"
      redirect_to root_url
    else
      render :new
    end
  end

  def show
    @follow = current_user.active_relationships.build
    @unfollow = current_user.active_relationships.find_by followed_id: @user.id
    @microposts = @user.microposts.by_desc.paginate page: params[:page],
      per_page: Settings.per_page_count
    redirect_to(root_url) && return unless logged_in?
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t ".update.messages.success"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = t ".user_deleted"
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :activation_digest
  end

  def correct_user
    redirect_to(root_url) unless current_user.current_user? @user
  end

  def find_user
    @user = User.find_by id: params[:id]

    return if @user
    flash[:danger] = t ".show.notfound"
    redirect_to root_url
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.gravatar.size}
    gravatar_id = Digest::MD5.hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_with model: @follow, remote: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit t(".follow_btn"), class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user.current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render "unfollow" %>
  <% else %>
    <%= render "follow" %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user, local: true, url: yield(:use_path) do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <%= f.label User.human_attribute_name :name %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label User.human_attribute_name :email %>
    <%= f.email_field :email, class: "form-control" %>

    <%= f.label User.human_attribute_name :password %>
    <%= f.password_field :password, class: "form-control" %>

    <%= f.label User.human_attribute_name :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>

    <%= f.submit yield(:button_text) , class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with model: @unfollow,
             html: { method: :delete },
             remote: true do |f| %>
  <%= f.submit t(".unfollow_btn"), class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.gravatar.list_size %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user.current_user?(user) %>
    | <%= link_to t(".delete"), user, method: :delete,
                                  data: { confirm: t(".delete_confirm") } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t(".page_name") %>
<% provide :button_text, t(".save_btn") %>
<% provide :use_path, user_path(current_user.id) %>
<h1><%= t ".page_title" %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t ".change"%></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".page_name") %>
<h1><%= t ".page_title"%></h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <%= render user %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide :title, t(".page_name") %>
<% provide :button_text, t(".create_account_btn") %>
<% provide :use_path, signup_path %>
<h1><%= t ".page_name" %></h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>
    </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render "follow_form" if logged_in? %>
    <% if @user.microposts.any? %>
      <h3><%= @user.microposts.count %> <%= t ".micropost"%></h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide :title, @title %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to t(".view_text"), @user %></span>
      <span><b><%= t ".microposts_cl" %></b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render "shared/stats" %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user,
            size: Settings.gravatar.mini_list_size), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate @users %>
    <% end %>
  </div>
</div>